<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtchSVd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtchSVd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWtchSVd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWtchSVd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWtchSVd\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'WtchSVd',
    'container.build_id' => 'c6fa2640',
    'container.build_time' => 1551193140,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtchSVd');
