<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUu5ePu2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUu5ePu2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUu5ePu2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUu5ePu2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUu5ePu2\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Uu5ePu2',
    'container.build_id' => '589b1bb3',
    'container.build_time' => 1550847790,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUu5ePu2');
