<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2VCJwpN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2VCJwpN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2VCJwpN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2VCJwpN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2VCJwpN\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '2VCJwpN',
    'container.build_id' => '56a89b83',
    'container.build_time' => 1551100812,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2VCJwpN');
